import {test} from "node:test";
import assert from "node:assert/strict";
import {setImmediate as tick} from "node:timers/promises";
import {ownershipHarness} from "./helpers/pi-ownership.ts";
async function until(f:()=>boolean){for(let i=0;i<30000;i++){if(f())return;await tick();}assert.fail("event barrier");}
async function turn(h:any,label:string){const before=h.children.length;const old=h.children.at(-1),n=old?.turns??0;const pending=h.session.prompt(label);await until(()=>h.children.length>before||old?.turns>n);const c=h.children.at(-1);if(c!==old)c.send({event:"init",conversation_id:label});await until(()=>c.turns>(c===old?n:0));await tick();c.step({step_type:"agent_response",text_delta:"answer"});c.result();await pending;assert.equal(c.spawnOptions.cwd,h.host.cwd);return h.session.sessionManager.getLeafId();}
for(const error of ["service unavailable","rate limit 429","quota exceeded","context length exceeded"])test(`CP4 real Pi retry enabled: ${error}`,async t=>{
 const h=await ownershipHarness();t.after(()=>h.close());h.session.setAutoRetryEnabled(true);h.session.setAutoCompactionEnabled(true);let retry=0;h.session.subscribe((e:any)=>{if(e.type==="auto_retry_start")retry++;});
 const pending=h.session.prompt("one harmless fake side effect");await until(()=>h.children.length===1);const c=h.children[0];c.send({event:"init",conversation_id:"X"});await until(()=>c.turns===1);await tick();c.send({event:"result",status:"ERROR",error});await pending;
 assert.equal(c.turns,1);assert.equal(h.children.length,1);assert.equal(retry,0);assert.equal(h.session.state.messages.at(-1)?.stopReason,"aborted");
});
test("CP4 real cwd initial fork restart and switch override",async t=>{const h=await ownershipHarness(true);t.after(()=>h.close());const tip=await turn(h,"initial");await h.host.fork(tip,{position:"at"});await turn(h,"fork");const file=h.session.sessionFile!;await h.host.dispose();await h.reopen(file);await turn(h,"restart");await h.host.switchSession(file,{cwdOverride:"/tmp"});await turn(h,"override");assert.equal(h.children.at(-1)!.spawnOptions.cwd,"/tmp");});
test("CP4 real Escape cancellation uses AbortSignal and lifecycle cleanup",async t=>{const h=await ownershipHarness();t.after(()=>h.close());const pending=h.session.prompt("cancel");await until(()=>h.children.length===1);const c=h.children[0];c.send({event:"init",conversation_id:"X"});await until(()=>c.turns===1);await h.session.abort();await pending;assert(c.killed);await turn(h,"fresh");await h.host.dispose();assert(h.children.every(c=>c.killed));});

test("CP4 real Pi pre-submission callback failure never retries",async t=>{const h=await ownershipHarness();t.after(()=>h.close());const original=h.session.agent.streamFunction;h.session.agent.streamFunction=(m:any,c:any,o:any)=>original(m,c,{...o,onPayload:async()=>{throw Error("service unavailable")}});h.session.setAutoRetryEnabled(true);await h.session.prompt("before submission");assert.equal(h.children.length,1);assert.equal(h.children[0].turns,0);});
test("CP4 real Pi length recovery cannot replay native work",async t=>{const h=await ownershipHarness();t.after(()=>h.close());h.session.setAutoCompactionEnabled(true);h.session.setAutoRetryEnabled(true);let compactions=0;h.session.subscribe((e:any)=>{if(e.type==="auto_compaction_start")compactions++;});const pending=h.session.prompt("native truncated work");await until(()=>h.children.length===1);const c=h.children[0];c.send({event:"init",conversation_id:"X"});await until(()=>c.turns===1);await tick();c.send({event:"result",status:"SUCCESS",result:{stop_reason:"MAX_TOKENS",usage:{input_tokens:1,output_tokens:1}},response:"partial"});await pending;assert.equal(h.children.length,1);assert.equal(c.turns,1);assert.equal(compactions,0);assert.equal(h.session.state.messages.at(-1)?.stopReason,"aborted");});
